ai_adoption: 
  outputs:   
    dev:     
      account: omodhph-hb03426  
      database: ai_adoption    
      password: xB-kWdma2YgHscg   
      role: ACCOUNTADMIN    
      schema: sariga     
      threads: 1     
      type: snowflake
      user: snowpythonuser 
      warehouse: ai_adoption_wh
  target: dev
